#! python3


#constants to ensure s
TAVERN = 'tavern'

DESC = 'desc'

NORTH = 'north'

SOUTH = 'south'

EAST = 'east'

WEST = 'west'

UP = 'up'

DOWN = 'down'

GROUND = 'ground'

SHOP = 'shop'

GROUNDDESC = 'grounddesc'

SHORTDESC = 'shortdesc'

LONGDESC = 'longdesc'

TAKEABLE = 'takeable'

EDIBLE = 'edible'

DESCWORDS = 'descwords'

BUYDESC = 'buydesc'








"""

The game world data is stored in a dictionary (which itself has dictionaries

and lists). Python's normal rules of indentation are suspended when typing out

a dictionary value until it encounters the closing curly brace, which is

helpful for us to make the dictionary value readable.



Each dictionary value inside the world variable is a different area in the

game world. The key is a string (i.e. 'Town Square') that is the reference

name of the location. It will also be displayed as the title of the area.



The value is another dictionary, which has keys 'desc', 'north', 'south',

'east', 'west', 'up', 'down', 'shop', and 'ground'. We use the constant

variables (e.g. DESC, NORTH, etc.) instead of strings in case we make

typos.



DESC is a text description of the area. SHOP, if it exists, is a list of

items that can be bought at this area. (We don't implement money in this

program, so everything is free.) GROUND is a list of items that are on

the ground in this area. The directions (NORTH, SOUTH, UP, etc.) are the

areas that exist in that direction.

"""



worldRooms = {
    'The Creaky Tankard Tavern' : {

      DESC: """
      You awake inside the creaky tankard tavern. The fire crackles in the background, 
      emanating a fuzzy orange light. The air is warm and smells of Ale and mead. 
      To move, type “n” or “north” to go in the northern direction “south” to go in the southern direction,
       “east” to go east, and “west” to go west. You can also go up or down, if the situation suits those commands.
        “look” will give you a description of the area. Type “help” to find a full list of commands and actions.""",

      NORTH: 'Town Square',

      EAST: 'Bartender',

      GROUND: []
    },

    '...': {

        DESC: """It looks like you couldn’t handle your liquor. Before you can move a muscle, you begin to feel your consciousness slipping away and the musty Tavern floor beckoning you into it’s comforting arms as you fall off the barstool.\n
        -=The Next Morning=- 
        You open your eyes to a familiar sight, the Creaky Tankard Tavern. From where you awoke you are staring directly upwards at the lanterns hung on the ceiling and the underbelly of the ba table, oh, you’re on the floor. Fortunately for you, the bar keepers must have been too exhausted to drag you out onto the streets.
        """,

        NORTH: 'Town Square',

        GROUND: ['Broken Whiskey Bottle']},

    'Town Square': {

        DESC: 'The town square is a large open space with a fountain in the center. Streets lead in all directions.',

        NORTH: 'North Y Street',

        EAST: 'East X Street',

        SOUTH: 'South Y Street',

        WEST: 'West X Street',

        TAVERN: 'The Creaky Tankard Tavern',

        GROUND: ['Welcome Sign', 'Fountain']},

        'Bartender': {
       
        DESC:'You approach the bartender. He’s stout and clean-shaven, donning a ragged white button-up shirt that looks like it’s seen a few too many days without a wash. - “Good evening to you weary adventurer, what can I do ya for?”(type “list” for a list of items)', 
        
        TAVERN:'...',
       
        SHOP: ['Honey Mead'],
       
        EAST:'...',
       
        WEST:'...',
       
        SHOP: ['Honey Mead', 'Stiffler Amber Ale', 'Bubbling Cider', 'Wine'],
       
        GROUND:['Barstool']},

    'North Y Street': {

        DESC: 'The northern end of Y Street has really gone down hill. Pot holes are everywhere, as are stray cats, rats, and wombats.',

        WEST: 'Thief Guild',

        EAST: 'Bakery',

        SOUTH: 'Town Square',

        GROUND: ['Do Not Take Sign Sign']},

    'Thief Guild': {

        DESC: 'The Thief Guild is a dark den of unprincipled types. You clutch your purse (though several other people here would like to clutch your purse as well).',

        SOUTH: 'West X Street',

        EAST: 'North Y Street',

        GROUND: ['Lock Picks', 'Silly Glasses']},

    'Bakery': {

        DESC: 'The delightful smell of meat pies fills the air, making you hungry. The baker flashes a grin, as he slides a box marked "Not Human Organs" under a table with his foot.',

        WEST: 'North Y Street',

        SOUTH: 'East X Street',

        SHOP: ['Meat Pie', 'Donut', 'Bagel'],

        GROUND: ['Shop Howto']},

    'West X Street': {

        DESC: 'West X Street is the rich section of town. So rich, they paved the streets with gold. This probably was not a good idea. The thief guild opened up the next day.',

        NORTH: 'Thief Guild',

        EAST: 'Town Square',

        SOUTH: 'Blacksmith',

        WEST: 'Used Anvils Store',

        GROUND: []},

    'Used Anvils Store': {

        DESC: 'The anvil store has anvils of all types and sizes, each previously-owned but still in servicable condition. However, due to a bug in the way this game is designed, you can buy anvils like any other item and walk around, but if you drop them they cannot be picked up since their TAKEABLE value is set to False. The code should be changed so that it\'s not possible for shops to sell items with TAKEABLE set to False.',

        EAST: 'West X Street',

        SHOP: ['Anvil'],

        GROUND: ['Anvil', 'Anvil', 'Anvil', 'Anvil']},

    'East X Street': {

        DESC: 'East X Street. It\'s like X Street, except East.',

        NORTH: 'Bakery',

        WEST: 'Town Square',

        SOUTH: 'Wizard Tower',

        GROUND: []},

    'Blacksmith': {

        DESC: 'The blacksmith loudly hammers a new sword over her anvil. Swords, axes, butter knives all line the walls of her workshop, available for a price.',

        NORTH: 'West X Street',

        EAST: 'South Y Street',

        SHOP: ['Sword', 'War Axe', 'Chainmail T-Shirt'],

        GROUND: ['Anvil', 'Shop Howto']},

    'South Y Street': {

        DESC: 'The Christmas Carolers of South Y Street are famous for all legally changing their name to Carol. They are also famous for singing year-round, in heavy fur coats and wool mittens, even in the summer. That\'s dedication to their craft!',

        NORTH: 'Town Square',

        WEST: 'Blacksmith',

        GROUND: []},

    'Wizard Tower': {

        DESC: 'Zanny magical antics are afoot in the world-famous Wizard Tower. Cauldrons bubble, rats talk, and books float midair in this center of magical discovery.',

        NORTH: 'East X Street',

        UP: 'Observation Deck',

        GROUND: ['Crystal Ball', 'Floating Book', 'Floating Book']},

    'Observation Deck': {

        DESC: 'You can see the entire town from the top of the Wizard Tower. Everybody looks like ants, especially the people transformed into ants by the wizards of the tower!',

        DOWN: 'Wizard Tower',

        UP: 'Magical Escalator to Nowhere',

        GROUND: ['Telescope']},

    'Magical Escalator to Nowhere': {

        DESC: 'No matter how much you climb the escalator, it doesn\'t seem to be getting you anywhere.',

        UP: 'Magical Escalator to Nowhere',

        DOWN: 'Observation Deck',

        GROUND: []},

    }



"""

This is the index of all possible items in the game world. Note that These

key-value pairs are more like blueprints than actual items. The actual

items exist in the GROUND value in an area's entry in the world variable.



The GROUNDDESC value is a short string that displays in the area's description.

The SHORTDESC value is a short string that will be used in sentences like, "You

drop X." or "You buy X."

The LONGDESC value is displayed when the player looks at the item.

The TAKEABLE Boolean value is True if the player can pick up the item and put

it in their inventory.

The DESCWORDS value is a list of strings that can be used in the player's

commands. For example, if this is ['welcome', 'sign'] then the player can type

a command such as "take sign" or "look welcome".

The TAKEABLE value is True if the item can be picked up off the ground. If

this key doesn't exist, it defaults to True.

The EDIBLE value is True if the item can be eaten. If this key doesn't exist,

it defaults to False.

"""

worldItems = {

    'Honey Mead': {

        GROUNDDESC: 'A suspicious meat pie rests on the ground.',

        SHORTDESC: 'honey mead',

        LONGDESC: 'A pint of mead, tastes like mead',

        BUYDESC: 'The bartender sinks beneath the Oak plank bar table. While he’s doing this, you notice how weathered and ' '\n'' worn the table is after years of abuse from unruly patrons. Before you can stare''\n'' for too long, the barman catches your eyes again, only this time holding a plain but a delicious-looking glass of mead in his hands.',

        EDIBLE: True,

        DESCWORDS: ['honey', 'mead']},

    'Stiffler Amber Ale': {

        GROUNDDESC: 'A suspicious meat pie rests on the ground.',

        SHORTDESC: 'Stiffler Amber Ale',

        LONGDESC: 'A tankard brimming with ale',

        BUYDESC: 'The bartender calls over to a passing barmaid with rows of heavy pint glasses full of radiant golden Ale. It\'s such an entrancing sight to behold you almost don\'t notice\n the barman zipping up his pants.',

        EDIBLE: True,

        DESCWORDS: ['stiffler', 'amber', 'ale']},

    'Bubbling Cider': {

        GROUNDDESC: 'A suspicious meat pie rests on the ground.',

        SHORTDESC: 'bubbling cider',

        LONGDESC: 'An enthralling chalice of cider',

        BUYDESC: 'You rack your brain thinking about what devilish incantations were involved\n in concocting this bubbling beverage.',

        EDIBLE: True,

        DESCWORDS: ['bubbling', 'cider']},

    'Wine': {

        GROUNDDESC: 'A pristine glass of wine',

        SHORTDESC: 'A pristine glass of wine',

        LONGDESC: 'A pristine glass containing a fiery and stupefying crimson red beverage.',

        BUYDESC: 'Here\'s your wine, you snob.',

        EDIBLE: True,

        DESCWORDS: ['wine']},

    'Welcome Sign': {

        GROUNDDESC: 'A welcome sign stands here.',

        SHORTDESC: 'a welcome sign',

        LONGDESC: 'The welcome sign reads, "Welcome to this text adventure demo. You can type "help" for a list of commands to use. Be sure to check out Al\'s cool programming books at http://inventwithpython.com"',

        TAKEABLE: False,

        DESCWORDS: ['welcome', 'sign']},

        'Broken Whiskey Bottle': {

        GROUNDDESC: 'A broken bottle lies on the floor',

        SHORTDESC: 'a broken bottle',

        LONGDESC: 'You struggle to regain your mental faculties in order to look around but strangely enough you don’t have to look too hard. Right beside you is a broken bottle of rum.',

        TAKEABLE: True,

        DESCWORDS: ['welcome', 'sign']},

    'Do Not Take Sign Sign': {

        GROUNDDESC: 'A sign stands here, not bolted to the ground.',

        SHORTDESC: 'a sign',

        LONGDESC: 'The sign reads, "Do Not Take This Sign"',

        DESCWORDS: ['sign']},

    'Fountain': {

        GROUNDDESC: 'A bubbling fountain of green water.',

        SHORTDESC: 'a fountain',

        LONGDESC: 'The water in the fountain is a bright green color. Is that... gatorade?',

        TAKEABLE: False,

        DESCWORDS: ['fountain']},
    'Barstool': {

        GROUNDDESC: 'You tipped over a barstool',

        SHORTDESC: 'a barstool',

        LONGDESC: 'an entirely unremarkable and worn bartsool, nothing interesting about it',

        TAKEABLE: False,

        DESCWORDS: ['barstool']},

    'Sword': {

        GROUNDDESC: 'A sword lies on the ground.',

        SHORTDESC: 'a sword',

        LONGDESC: 'A longsword, engraved with the word, "Exkaleber"',

        DESCWORDS: ['sword', 'exkaleber', 'longsword']},

    'War Axe': {

        GROUNDDESC: 'A mighty war axe lies on the ground.',

        SHORTDESC: 'a war axe',

        LONGDESC: 'The mighty war axe is made with antimony impurities from a fallen star, rendering it surpassingly brittle.',

        DESCWORDS: ['axe', 'war', 'mighty']},

    'Chainmail T-Shirt': {

        GROUNDDESC: 'A chainmail t-shirt lies wadded up on the ground.',

        SHORTDESC: 'a chainmail t-shirt',

        LONGDESC: 'The chainmail t-shirt has a slogan and arrow engraved on the front: "I\'m with Stupid"',

        DESCWORDS: ['chainmail', 'chain', 'mail', 't-shirt', 'tshirt', 'stupid']},

    'Anvil': {

        GROUNDDESC: 'The blacksmith\'s anvil, far too heavy to pick up, rests in the corner.',

        SHORTDESC: 'an anvil',

        LONGDESC: 'The black anvil has the word "ACME" engraved on the side.',

        TAKEABLE: False,

        DESCWORDS: ['anvil']},

    'Lock Picks': {

        GROUNDDESC: 'A set of lock picks lies on the ground.',

        SHORTDESC: 'a set of lock picks',

        LONGDESC: 'A set of fine picks for picking locks.',

        DESCWORDS: ['lockpicks', 'picks', 'set']},

    'Silly Glasses': {

        GROUNDDESC: 'A pair of those silly gag glasses with the nose and fake mustache rest on the ground.',

        SHORTDESC: 'a pair of silly fake mustache glasses',

        LONGDESC: 'These glasses have a fake nose and mustache attached to them. The perfect disguise!',

        DESCWORDS: ['glasses', 'silly', 'fake', 'mustache']},

    'Meat Pie': {

        GROUNDDESC: 'A suspicious meat pie rests on the ground.',

        SHORTDESC: 'a meat pie',

        LONGDESC: 'A meat pie. It tastes like chicken.',

        EDIBLE: True,

        DESCWORDS: ['pie', 'meat']},

    'Bagel': {

        GROUNDDESC: 'A bagel rests on the ground. (Gross.)',

        SHORTDESC: 'a bagel',

        LONGDESC: 'It is a donut-shaped bagel.',

        EDIBLE: True,

        DESCWORDS: ['bagel']},

    'Donut': {

        GROUNDDESC: 'A donut rests on the ground. (Gross.)',

        SHORTDESC: 'a donut',

        LONGDESC: 'It is a bagel-shaped donut.',

        EDIBLE: True,

        DESCWORDS: ['donut']},

    'Crystal Ball': {

        GROUNDDESC: 'A glowing crystal ball rests on a small pillow.',

        SHORTDESC: 'a crystal ball',

        LONGDESC: 'The crystal ball swirls with mystical energy, forming the words "Answer Unclear. Check Again Later."',

        DESCWORDS: ['crystal', 'ball']},

    'Floating Book': {

        GROUNDDESC: 'A magical book floats here.',

        SHORTDESC: 'a floating book',

        LONGDESC: 'This magical tomb doesn\'t have a lot of pictures in it. Boring!',

        DESCWORDS: ['book', 'floating']},

    'Telescope': {

        GROUNDDESC: 'A telescope is bolted to the ground.',

        SHORTDESC: 'a telescope',

        LONGDESC: 'Using the telescope, you can see your house from here!',

        TAKEABLE: False,

        DESCWORDS: ['telescope']},


    'Shop Howto': {

        GROUNDDESC: 'A "Shopping HOWTO" note rests on the ground.',

        SHORTDESC: 'a shopping howto',

        LONGDESC: 'The note reads, "When you are at a shop, you can type "list" to show what is for sale. "buy <item>" will add it to your inventory, or you can sell an item in your inventory with "sell <item>". (Currently, money is not implemented in this program.)',

        EDIBLE: True,

        DESCWORDS: ['howto', 'note', 'shop']},

    }

